### ISSUE TITLE
"Show file in folder" always open My Documents

### ISSUE THREAD

**Issue by elshekar** [soywiz/vitaorganizer#22]
Hi there

Yesterday I noticed in 0.4 that "Show file in folder" always open the same folder: "My Documents" (in Windows OS).

Tested in two PC's. One with Windows 10 x32 and another with Windows 8.1 x32. No matter if my VPK are in a network unit or in my hard drive

Thanks for your job! ;)

**Comment by soywiz** [comment]
Uhm. That's strange. Can you tell my if the path `C:/path/to/files/file.vpk` has spaces, accents or special characters?

**Comment by elshekar** [comment]
Yes, the problem with no doubt are the spaces. Remember I am in Windows OS. In that example, I have two files in the same folder "C:\Users\CAUSAE\Downloads\Dragons_Crown_PCSE-00019", called "PCSE00019_FULLGAME_01.00_C0_V2.0" and "PCSE00019_UPDATE_01.06_C0_V2.0"

1) Show file in folder always focus on the update PCSE00019_UPDATE_01.06_C0_V2.0
2) If i add a space in the update, for example PCSE00019_UPD ATE_01.06_C0_V2.0, opens My Documents
3) If I move the PCSE00019_UPDATE_01.06_C0_V2.0 no another folder (leaving only PCSE00019_FULLGAME_01.00_C0_V2.0) it is located and focused perfectly
4) If I only leave the game without the update, and add a space (PCSE00019_FUL LGAME_01.00_C0_V2.0) opens My Document
5) If I add a space to a folder path ( C:\Users\CAUSAE\Downloads\Dragons_Cro wn_PCSE-00019\PCSE00019_FULLGAME_01.00_C0_V2.0" open My Documents

Conclusion: Any space in the path opens MyDocuments. Plus, strange things happen with >1 archives (updates for example). The second example is curious becouse the game exist, but focusses on the update and becouse have an space, opens My Documents

Gracias campeón ;)
