### ISSUE TITLE
A way to know Vitamin version

### ISSUE THREAD

**Issue by elshekar** [soywiz/vitaorganizer#23]
[If that's true ](https://www.reddit.com/r/VitaPiracy/comments/52ncy8/is_there_a_way_to_tell_the_difference_between_10/) maybe you can add a Column to know the VITAMIN/MAI Version used in order to have an updated library ;)

Edit: Maybe the region too ;). I supose that you can know this only with the name code. I supose every version have a diferent code

Thanks

**Comment by luckylucks** [comment]
I have added it in my [fork](https://github.com/luckylucks/vitaorganizer). Mai version only functions for the old? (same format as vitamin) version, the other version uses a different directory hierarchy.

**Comment by soywiz** [comment]
Already merged.
