### ISSUE TITLE
Java.lang.OutOfMemoryError: Java heap space error

### ISSUE THREAD

**Issue by Sharinnengnan** [soywiz/vitaorganizer#25]
Hi guys , i got this error when i try to copy a game on my vita with vita organiser ... I tried with attack on titan and at the end of the installation there is the folder in ux0 app but no eboot in that folder so no bubble in my vita ... I can t play the game...

**Comment by gordon0001** [comment]
try starting it with more maximum heap

java -Xmx512M -jar .\vitaorganizer-0.4.jar

**Comment by Sharinnengnan** [comment]
Can you explain more ? I really don't know anything about java and all that stuff...

**Comment by Ivoyko** [comment]
Same error with Attack on Titan and Persona 4 Golden.
