### ISSUE TITLE
NO DETECTING BACKUP

### ISSUE THREAD

**Issue by Ivoyko** [soywiz/vitaorganizer#26]
I have a lot of backups and all are detected less my Sword Art Online Hollow Fragment. The backup its ok because i did it myself and i tried it when i finished installing the dump.

**Comment by soywiz** [comment]
Can you send me a like where I can download the file so I can check it? I actually own that game phisically, but not dumped it. Send it to: soywiz@gmail.com

**Comment by soywiz** [comment]
It works for me:
![hollow](https://cloud.githubusercontent.com/assets/570848/18607604/df77cbb0-7cd1-11e6-9f28-858f6ef8cbb5.png)

Please try to delete `vitaorganizer/cache` folder that should be along the `vitaorganizer.exe/jar`

**Comment by soywiz** [comment]
Talked already by email. Seems to work now.

**Comment by Ivoyko** [comment]
Yeah you are a boss mage guy

________________________________
De: Carlos Ballesteros Velasco <notifications@github.com>
Enviado: sábado, 17 de septiembre de 2016 16:10
Para: soywiz/vitaorganizer
Cc: ivoyko; Author
Asunto: Re: [soywiz/vitaorganizer] NO DETECTING BACKUP (#26)


Talked already by email. Seems to work now.

-
