### ISSUE TITLE
Convert MAI backups into VPK?

### ISSUE THREAD

**Issue by soywiz** [soywiz/vitaorganizer#27]
I should try to be able to convert rar files into a single VPK so it works on vitaorganizer. Or that vitaorganizar supports both.

**Comment by paweloszu** [comment]
That would be a very useful feature.

**Comment by RijjiResa** [comment]
Would be greatly appreciated.

**Comment by HorikawaOtane** [comment]
Yeah, agreed.

**Comment by soywiz** [comment]
As far as I investigated installing VPK/ZIP files from Mai, leads to error at VitaShell. I have to investigate whether I can to install a fake working eboot.bin and later replace it or try to put filese that do not fail to install and then replace them with mai's ones. As it seems that the installed file is the same as in the dump folder.
