### ISSUE TITLE
???? in Russian Translate

### ISSUE THREAD

**Issue by pvc1** [soywiz/vitaorganizer#30]
all words in russian version was changed in ??????, what the problem ?

**Comment by soywiz** [comment]
Wow. That's true. Didn't noticed :(
Probably related to an encoding issue. Going to fix it now.

**Comment by paweloszu** [comment]
There is also problem with displaying polish specific characters (ąćęłńśźż) they are replaced with some strange symbols. 
![image](https://cloud.githubusercontent.com/assets/22132252/18618439/27150d78-7de7-11e6-945b-41593479a81c.png)

**Comment by gordon0001** [comment]
you need to escape them

use http://www.fileformat.info/info/unicode/ 
search your character and look for "C/C++/Java source code" under encodings. 
like \u00F6 for ö

**Comment by soywiz** [comment]
It it s pity how java handle .properties and bundles. It should be all UTF-8. But it is not the case, but I will try some tricks in order to see wether I can use UTF-8 directly so no escaping is needed at all.

**Comment by soywiz** [comment]
Released 0.5.1. Now it properly supports UTF-8. Also I have added a menu to select language, so I will be able to preview languages and find out whether they are ok or not. Sorry for the inconvenience, and thanks for the translation!
