### ISSUE TITLE
Font issue (polish language) and ability to separate updates.

### ISSUE THREAD

**Issue by szczuru** [soywiz/vitaorganizer#31]
Hi, there is an issue with font with special characters (eg diacritital charts in polish lang):

![image](https://cloud.githubusercontent.com/assets/17336164/18619463/6a00cdd2-7dfd-11e6-8c15-3fab7abf7f96.png)

![image](https://cloud.githubusercontent.com/assets/17336164/18619474/a16225c8-7dfd-11e6-8e24-bca99ace678e.png)

And is there any way to show on games list updates too? Eg i have 2 vpks 1 with base game v1.00 and second vpk with 1.1 update.

**Comment by soywiz** [comment]
Probably an encoding issue. Going o check it.

Right now it is not possible to differentiate game from update. But I will check it! Thanks!

**Comment by soywiz** [comment]
0.5.1 fixes polish. Sorry for the inconvenience!
