### ISSUE TITLE
Latest 0.5.1 not working!

### ISSUE THREAD

**Issue by DaminavPL** [soywiz/vitaorganizer#38]
Hi, latest build nod working. Files VPK are not sending to Vita :-/

**Comment by gordon0001** [comment]
yes, its throwing lots of exceptions, but its sending the promiting vpk, installs it and it sends the data, but no status is being shown in the statusbar. at the end it shows a messagebox that it successfully installed the game, and of course its working

**Comment by DaminavPL** [comment]
On my side: Sending VPK and then I have Complete message but Icon is blank and game is not send on vita :-/ Using VitaShell install works :-/ WTH??

**Comment by DaminavPL** [comment]
This is crazy. Why new version don't have progress information?
Only Installing vpk... Can you make progress bar of installing in "%" and FTP speed information?

**Comment by soywiz** [comment]
It seems to be a bug, I will check it and release a version fixing it tonight (0.5.2)
