### ISSUE TITLE
Issues with Russian Language

### ISSUE THREAD

**Issue by panther666** [soywiz/vitaorganizer#40]
In latest version on russian win7 i see "???????" instead of letters.
http://jpegshare.net/c7/b8/c7b83fe4e6588ce703747702c3dff8c9.jpg.html

And i think we need option in the menu to change language.

**Comment by soywiz** [comment]
That's exactly what 0.5.1 fixes (????) and includes (language selector) :)
Though it seems that 0.5.1 has a critical bug that doesn't allow to send games to psvita via ftp, so stick to 0.4. I will release 0.5.2 tonight.
