### ISSUE TITLE
Troubles in 0.5.2

### ISSUE THREAD

**Issue by TERMiN8** [soywiz/vitaorganizer#51]
1) Option "Repack" don't rename .temp in .vpk
2) Please add option rename .vpk in format: Title_VERSION_ID

**Comment by gordon0001** [comment]
1) repack works fine for me. only if an error occured while repacking i could imagine it wouldnt delete it
2) ID_TITLE_VERSION would be better, but we can add several format options

i also suggest to add an entry to the options menu to clear the cache files. i did yesterday delete them and finally all my vpks were shown, just one was missing.

**Comment by TERMiN8** [comment]
After Repack info Comression level: 8

**Comment by soywiz** [comment]
The displayed compression level 8 is a mistake. 8 means that it is compressed but cannot determine which level so it will just display 0 for uncompressed and 8 for any compression level. I will fix it in next version.

**Comment by DaminavPL** [comment]
Sending Phantasy Star NOVA vitaorganizer send only 148,7MB! Is this a bug?
Game have large file 2,8GB is this a problem to vitaorganizer?? Can you fix that?

**Comment by gordon0001** [comment]
the same i noticed with ragnarok odyssey ace. it also only sends the update. its on my TODO list

**Comment by TERMiN8** [comment]
Upload VPK freeze after minymize VitaOrganizer window.

**Comment by soywiz** [comment]
Closing this as long as 0.6.0 is out. Please check stuff in there. GAME/UPDATE is already shown separately.
The freeze sounds strange. It would be a timeout from the psvita?
The option for renaming all vpk is a separate feature not a problem that should be reported separately, and it is reported already here: https://github.com/soywiz/vitaorganizer/issues/6
