### ISSUE TITLE
.52 not working

### ISSUE THREAD

**Issue by narutonyo29** [soywiz/vitaorganizer#54]
vita organizer .52 cannot detect any vpk,,,,i have .3 and i detect the vpk..what is seems to be the prob??hope for answers ..tia

**Comment by gordon0001** [comment]
well, we can only do guessing. you dont provide much info.

download the .jar version of 0.5.2, open the commandline or powershell and run "java -jar ./vitaorganizer-0.5.2,jar
it should give you a list a of scanned vpks or maybe you see some exceptions, then you have to tell us them.
also try to delete to cache files (delete the folder vitaorganizer, its in the same place where vitaorganizer-0.5.2.jar/exe is
did you select the correct vpk folder with the button "Select folder.."? What does it say at the statusbar (the bar on the button of the app) when you start the vitaorganizer? It should say that it is analyzing files

**Comment by LeoXX** [comment]
I also have empty window, errors like:
```
Error processing PCSE00762_Norn9 var Commons_01.00_USA_V2.0.VPK
java.lang.ClassCastException: java.util.zip.ZipFile cannot be cast to java.io.Closeable
        at com.soywiz.vitaorganizer.VpkFile.cacheAndGetGameId(VpkFile.kt:50)
        at com.soywiz.vitaorganizer.tasks.UpdateFileListTask.perform(UpdateFileListTask.kt:38)
        at com.soywiz.vitaorganizer.VitaTaskQueue$thread$1.run(VitaTaskQueue.kt:14)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by soywiz** [comment]
Which java version did you have? Java6?

**Comment by soywiz** [comment]
I have put a java7 requirement for >= 0.6.1, now travis checks that it works on java7 but not java6. So we shouldn't have regressions on this. For example I was using Process.isAlive recently that was just available on java8 and that break java7 and java6. As far as I know java7 in available on windows xp. So windows xp users are still covered. I'm closing this. Please feel free to reopen if you still have issues with this.
