### ISSUE TITLE
Preserve window size/state

### ISSUE THREAD

**Issue by soywiz** [soywiz/vitaorganizer#62]

**Comment by soywiz** [comment]
The idea here is to restore the window size after reopening the application. I'm already storing successfully the last window size before the application is closed, but when trying to restore after opening it, it doesn't do anything.

@gordon0001 I tried this, but failed miserably. It would take more time, since I don't have too much experience with awt. Do you know how to do this? I tried `JFrame.setSize`, but didn't do anything. Do you know what's wrong with it? If you know how to fix this can you do this task?

**Comment by gordon0001** [comment]
i can try, but i am not so experienced in java or kotlin. intellij runs very poorly on  my win10 convertible laptop (only 2gb ram) but i can kinda work with it.

as far as i figured out 
> table.table.preferredScrollableViewportSize = Dimension(960, 600)
that kinda affects the size of the frame. will investigate further, since i had some particial success
