### ISSUE TITLE
Automatically check for updates

### ISSUE THREAD

**Issue by soywiz** [soywiz/vitaorganizer#67]
We can make it check for updates once a week or so, so people doesn't miss updates. We can store the last checked timestamp in the settings.

**Comment by gordon0001** [comment]
should i add something like that or are you already working on it?

**Comment by soywiz** [comment]
I'm not working on it yet. If you have some time, feel free to work on it. If not, I would implent it this weekend.

**Comment by gordon0001** [comment]
working now on it

**Comment by gordon0001** [comment]
can take some time. found some things to improve in the updatetask. also want to let the user choose a timespan to check for updates, and for that i would like to introduce a general settings/options dialog window. also needed for the future (multiple vpk paths, more and more settings).

i think i commit first the fixed timespan version with 1 week, and then i have time to implement the settings dialog. 

for the "vpk install" file selection dialog i would like to have here the last remembered directory where you installed a vpk from instead always using the vpkdir as startdir. but this can be a setting entry in the settings dialog aswell

what you think about that?

**Comment by soywiz** [comment]
I like the idea. Also creating a settings dialog would allow to add more settings later.
